# Generated by Django 2.1.3 on 2018-11-13 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Символльный код')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=400, verbose_name='SEO Description')),
                ('top_text', models.TextField(blank=True, max_length=2000, verbose_name='Верхний текст')),
                ('bottom_text', models.TextField(blank=True, max_length=2000, verbose_name='Нижний текст')),
                ('activate', models.BooleanField(default=True, verbose_name='Категория включена')),
                ('level', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='shop.Category', verbose_name='Родительское категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Символьный код')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=400, verbose_name='SEO Description')),
                ('text_description', models.TextField(blank=True, max_length=2000, verbose_name='Описание')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('status', models.CharField(choices=[('В наличии', 'В наличии'), ('Под заказ', 'Под заказ')], default='in_stock', max_length=50, verbose_name='Статус')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_products', to='shop.Category', verbose_name='Главная категория')),
                ('secondary_categories', models.ManyToManyField(blank=True, related_name='secondary_products', to='shop.Category', verbose_name='Родительские категории')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product-photo/')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Product')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
