# Generated by Django 2.1.3 on 2018-11-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181114_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='uniq_hid',
            field=models.PositiveIntegerField(default=1542226672),
        ),
    ]
