# Generated by Django 2.1.3 on 2018-11-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_uniq_hid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='uniq_hid',
        ),
    ]
