# Generated by Django 2.1.3 on 2018-11-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_category_uniq_hid'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
