# Generated by Django 2.1.3 on 2018-11-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_sort_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sort_name',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
