# Generated by Django 2.1.3 on 2018-11-16 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20181116_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_products', to='shop.Category', verbose_name='Хлебные крошки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_categories',
            field=models.ManyToManyField(related_name='secondary_products', to='shop.Category', verbose_name='Родительские категории'),
        ),
    ]
