# Generated by Django 2.1.3 on 2018-11-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20181116_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('total', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, help_text='Отключенные товары исчезают с сайта', verbose_name='Товар включен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='В эту категорию будет вложен товар по хлебным крошкам', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_products', to='shop.Category', verbose_name='Вложенность по хлебным крошкам'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='Целое число в рублях. Без копеек.', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_categories',
            field=models.ManyToManyField(help_text='Товар будет выводиться в выбранных категориях.', related_name='secondary_products', to='shop.Category', verbose_name='Родительские категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Мета-описание. Пользователи его не видят, но поисковикам важно, чтобы оно было заполнено. Пустым оставлять можно, но не рекомендуется.', max_length=400, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Это поле будет заголовком страницы в браузере. Очень важное поле для поисковых систем. Заполнять нужно с умом', max_length=200, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Это адрес страницы. Если оставить поле пустым, он сгенерируется автоматически.', max_length=200, unique=True, verbose_name='Символьный код'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text_description',
            field=models.TextField(blank=True, help_text='\n            Текстовое описание поддерживает html-тэги. Нужно использовать их, если хочется отформатировать текст.<br> \n            Небольшая справка по тэгам:<br><br>\n            &lt;p&gt;В такой текст заключается абзац&lt;/p&gt; <br><br>\n            &lt;strong&gt;В таком тэге текст будет жирным&lt;/strong&gt; <br><br>\n            &lt;br&gt; - такой одинарный тэг используется для переноса строки\n        ', max_length=2000, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cart_item', to='shop.Product'),
        ),
    ]
