# Generated by Django 2.1.3 on 2018-11-24 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20181124_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='secondary_categories',
            field=models.ManyToManyField(blank=True, help_text='Товар будет выводиться в выбранных категориях.', related_name='secondary_products', to='shop.Category', verbose_name='Родительские категории'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='shop.Product'),
        ),
    ]
