# Generated by Django 2.1.3 on 2018-11-24 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20181124_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='name',
            field=models.CharField(blank=True, default='-', max_length=200, verbose_name='Название товара'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_item', to='shop.Product'),
        ),
    ]
