# Generated by Django 2.0.4 on 2018-11-25 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20181124_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(default='Не указано', max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(default='Москва', max_length=50)),
                ('delivery_address', models.CharField(max_length=200)),
                ('delivery_company', models.CharField(default='Не указано', max_length=100)),
                ('pay_type', models.CharField(max_length=50)),
                ('order_comments', models.TextField(max_length=500)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='shop.Cart')),
            ],
        ),
    ]
