# Generated by Django 2.1.3 on 2018-12-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20181201_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infopage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название страницы')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Символльный код')),
                ('content', models.TextField(max_length=3000, verbose_name='Содержание')),
                ('seo_title', models.CharField(max_length=200, verbose_name='SEO Title')),
                ('seo_description', models.CharField(max_length=400, verbose_name='SEO Description')),
            ],
        ),
    ]
