# Generated by Django 2.1.3 on 2018-12-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_infopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='show_in_menu',
            field=models.BooleanField(default=True, verbose_name='Выводить в меню'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Мета-описание. Пользователи его не видят, но поисковикам важно, чтобы оно было заполнено. Пустым оставлять можно, но не рекомендуется.', max_length=400, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Это поле будет заголовком страницы в браузере. Очень важное поле для поисковых систем. Заполнять нужно с умом', max_length=200, verbose_name='SEO Title'),
        ),
    ]
