# Generated by Django 2.1.3 on 2018-12-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20181202_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infopage',
            options={'verbose_name': 'Информационная страница', 'verbose_name_plural': 'Информационные страницы'},
        ),
    ]
